Added option to build examples or not.
jfrasch/qpDUNES pull request #8
Opened 2016-09-19 10:06 UTC by mkotlyar

2016-09-19 10:42 UTC, mvukov commented on CMakeLists.txt
> +OPTION(QPDUNES_MAKE_EXAMPLES "Make qpDUNES examples" ON)
Please move this option to above where all other options reside.

2016-09-19 10:43 UTC, mvukov requested changes
one minor comment, otherwise LGTM!

2016-09-23 16:01 UTC, mkotlyar commented on CMakeLists.txt
> +OPTION(QPDUNES_MAKE_EXAMPLES "Make qpDUNES examples" ON)
Done

2016-09-23 17:16 UTC, mvukov approved these changes

2016-09-23 17:16 UTC, merged